# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications/ | grep Xcode
    - name: Select latest Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build for iOS Simulator
      run: xcodebuild -project monitor.xcodeproj -scheme monitor -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build CODE_SIGNING_ALLOWED=NO
    - name: Run tests on iOS Simulator
      run: xcodebuild -project monitor.xcodeproj -scheme monitor -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' test CODE_SIGNING_ALLOWED=NO
