# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -project monitor.xcodeproj -scheme monitor -destination 'platform=macOS' build
    - name: Run tests
      run: xcodebuild -project monitor.xcodeproj -scheme monitor -destination 'platform=macOS' test
